

# ---------------------------------------
# 1) Word list (your 5-letter dictionary)
# ---------------------------------------
words = [
"able","about","above","abuse","actor","acute","adapt","adept","admin","admit",
"adobe","adopt","adore","adult","after","again","agent","agile","aging","agree",
"ahead","aisle","alarm","album","alert","alien","align","alike","alive","alloy",
"allow","alone","along","alter","amber","amend","among","ample","amuse","angel",
"anger","angle","angry","ankle","apart","apple","apply","apron","arena","argue",
"arise","armed","armor","aroma","array","arrow","aside","asset","atlas","audio",
"audit","avail","avoid","await","awake","award","aware","awful","badge","badly",
"baker","bases","basic","basis","basin","batch","beach","beard","beast","began",
"begin","begun","being","below","bench","berry","birth","black","blade","blame",
"blank","blast","blaze","bleed","blend","bless","blind","block","blood","bloom",
"board","boast","bonus","boost","booth","bound","brain","brake","brand","brave",
"bread","break","breed","brief","brick","bride","bring","brink","broad","broke",
"brown","brush","build","built","burst","buyer","cable","camel","candy","carry",
"carve","catch","cause","chain","chair","chalk","chant","chaos","charm","chart",
"chase","cheap","cheat","check","cheer","chest","chief","child","china","chill",
"choir","chose","civil","claim","clamp","class","clean","clear","clerk","click",
"climb","clock","close","cloth","cloud","coach","coast","color","could","count",
"court","cover","crack","craft","crash","crawl","crazy","cream","creed","creek",
"crime","crisp","cross","crowd","crown","crush","curve","cycle","daily","dance",
"dairy","dated","dealt","death","delay","depth","devil","diary","digit","dirty",
"doing","doubt","dozen","draft","drain","drama","drawn","dream","dress","drift",
"drill","drink","drive","drone","drunk","eagle","early","earth","eight","elite",
"empty","enemy","enjoy","enter","entry","equal","error","event","every","exact",
"exist","extra","faith","false","fault","favor","fiber","field","fierce","fifth",
"fifty","fight","final","first","fixed","flame","flash","fleet","floor","fluid",
"focus","force","forge","forth","forty","forum","found","frame","frank","fraud",
"fresh","front","frost","fruit","fully","funny","giant","given","glass","globe",
"glory","going","grace","grade","grand","grant","grass","great","green","greet",
"gross","group","grown","guard","guess","guest","guide","habit","happy","harsh",
"heart","heavy","hence","hobby","honor","horse","hotel","house","human","humor",
"ideal","image","index","inner","input","issue","ivory","joint","judge","known",
"label","labor","large","later","laugh","layer","learn","lease","least","leave",
"legal","level","light","limit","local","logic","loose","lower","lucky","lunch",
"magic","major","maker","march","match","maybe","mayor","meant","medal","media",
"metal","meter","might","minor","minus","mixed","model","money","month","moral",
"motor","mount","mouse","mouth","movie","music","needs","never","newly","night",
"noise","north","noted","novel","nurse","occur","ocean","offer","often","order",
"other","ought","paint","panel","paper","party","peace","phase","phone","photo",
"piece","pilot","pitch","place","plain","plane","plant","plate","point","pound",
"power","press","price","pride","prime","print","prior","prize","proof","proud",
"prove","queen","quick","quiet","quite","radio","raise","range","rapid","ratio",
"reach","ready","refer","right","rival","river","rough","round","route","royal",
"rural","scale","scene","scope","score","sense","serve","seven","shall","shape",
"share","sharp","sheet","shelf","shell","shift","shine","shirt","shock","shoot",
"short","shown","sight","since","sixth","sixty","skill","sleep","slide","small",
"smart","smile","smoke","solid","solve","sorry","sound","south","space","spare",
"speak","speed","spend","spent","split","spoke","sport","staff","stage","stand",
"start","state","steam","steel","stick","still","stock","stone","stood","store",
"storm","story","strip","stuck","study","stuff","style","sugar","suite","super",
"sweet","table","taken","taste","teach","teeth","thank","their","theme","there",
"these","thick","thing","think","third","those","three","throw","tight","times",
"tired","title","today","topic","total","touch","tough","tower","track","trade",
"train","treat","trend","trial","tried","tries","truck","truly","trust","truth",
"twice","under","union","unity","until","upper","upset","urban","usage","usual",
"valid","value","video","visit","vital","voice","waste","watch","water","wheel",
"where","which","while","white","whole","whose","woman","women","world","worry",
"worse","worst","worth","would","wound","write","wrong","wrote","yield","young",
"youth","zebra"
]

